services:
  - type: web
    name: driftaway-mock
    env: node
    buildCommand: "npm install --prefix frontend && npm run build --prefix frontend && npm install --prefix backend"
    startCommand: "node backend/index.js"
    healthCheckPath: /
